### ISSUE TITLE
[Crash] App crash on Android 6

### ISSUE THREAD

**Issue by pcuco** [pcuco/eSettings#2]
**Pre-Conditions**
Fresh install

**Steps**
User opens app

**Results**
App crash

**Additional Information**
`11-02 10:51:26.719: E/NEW_BHD(21002): Battery Power Supply logging Daemon start!!!!!
11-02 10:51:26.720: E/NEW_BHD(21002): Cannot run on production devices!
11-02 10:51:28.784: E/DataBuffer(3826): Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@3824c4f)
11-02 10:51:29.203: E/AndroidRuntime(21004): FATAL EXCEPTION: main
11-02 10:51:29.203: E/AndroidRuntime(21004): Process: com.app.esettings, PID: 21004
11-02 10:51:29.203: E/AndroidRuntime(21004): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.esettings/com.app.esettings.MainActivity}: java.lang.SecurityException: getLine1NumberForDisplay: Neither user 10094 nor current process has android.permission.READ_SMS.
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.os.Looper.loop(Looper.java:148)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at java.lang.reflect.Method.invoke(Native Method)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-02 10:51:29.203: E/AndroidRuntime(21004): Caused by: java.lang.SecurityException: getLine1NumberForDisplay: Neither user 10094 nor current process has android.permission.READ_SMS.
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.os.Parcel.readException(Parcel.java:1620)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.os.Parcel.readException(Parcel.java:1573)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getLine1NumberForDisplay(ITelephony.java:4101)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.telephony.TelephonyManager.getLine1NumberForSubscriber(TelephonyManager.java:2132)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.telephony.TelephonyManager.getLine1Number(TelephonyManager.java:2110)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at com.app.esettings.SIMCard.getNumber(SIMCard.java:20)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at com.app.esettings.MainActivity.onCreate(MainActivity.java:15)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.Activity.performCreate(Activity.java:6259)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
11-02 10:51:29.203: E/AndroidRuntime(21004): 	... 9 more
: E/(): Device disconnected: 1
: E/(): Device disconnected
`

**Comment by pcuco** [comment]
Issue fixed - https://github.com/pcuco/eSettings/commit/e6554ef90072c7046c3c77ff185e81dd1b88a9c7
